version: "3.8"

services:
  postgres:
    image: postgres
    container_name: posgresql_db
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=sotoAy4m
    ports:
      - '5434:5434'

  flask:
    container_name: flask
    image: dwihandoyo/email-saver:latest
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgres
    restart: always
    ports:
      - "5000:5000"

  cron:
    container_name: cron
    build: cron/.
    depends_on:
      - fastapi
    restart: always
